### ISSUE TITLE
PALE embedding: GPU memory nearly all occupied but utility is zero

### ISSUE THREAD

**Issue by w-zx** [Allen517/alp-baselines#1]
Hi, I am trying to train and test the PALE algorithm in Tensorflow GPU model, but when I was running
```
Step 2: matching (PALE)

python alp_main.py --embedding1 test.res.epoch5.node_order1 --embedding2 ffvm.res.epoch5.node --type-model lin --identity-linkage data/test.align --output test.alp --batch-size 4 --input-size 4 --epochs 10 --method pale --neg-ratio 5 --device :/cpu:0
```
Nearly all the GPU memory is used but the utility stayed zero, and I am using GTX1080Ti, python 2.7, tensorflow-gpu 1.10.0, cuda 9.0, cudnn 7.3.

May I ask if you have encountered into such problem and the hardware/software environment you were using? (I am worrying that it might be a config issue)

Thank you very much.

**Comment by Allen517** [comment]
The command "--device :/cpu:0" shows that you use cpu to run the code. I'm not clear why you still use gpu during the training process. Could you give me more detail about the problem?

**Comment by w-zx** [comment]
Thank you for the reply, I'm sorry I didn't make it clear enough, the actual command I used is:
```
python alp_main.py --embedding1 test.res.epoch5.node_order1 --embedding2 ffvm.res.epoch5.node --type-model lin --identity-linkage data/test.align --output test.alp --batch-size 4 --input-size 4 --epochs 10 --method pale --neg-ratio 5 --device :/gpu:0
```
So tensorflow will assign the task to GPU and I have seen such process via nvida-smi (the true CUDA version is 9.0, OS: Ubuntu 16.04)
![](https://ws3.sinaimg.cn/large/006tNc79gy1fz6aiflcbkj30yg0fujto.jpg)
However, the GPU utility remains 0, and I doubt that if it is really doing the training. But I didn't make any modification to the original code, so I wonder if I use the wrong config or more preparations need to be done before running?
Thank you.

**Comment by Allen517** [comment]
I re-run the code and find the problem located at 
``
pale/pale.py", line 184, in train_one_epoch
``
In test dataset, the validation progress would be invalid if there are no enough data for validation. In this way, the code would be trapped in Line 184 in pale.py.

I have upload the updated codes in the project. Thanks a lot for your proposed issue :-)

**Comment by w-zx** [comment]
Thank you very much for the response, I understood the reason and appreciate your work. Now the code could be processed correctly.
